# Generated by Django 4.2 on 2023-04-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_teacher_subject_delete_course_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
